# Generated by Django 4.2.4 on 2023-08-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
