# Generated by Django 4.2.4 on 2023-08-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
