# Generated by Django 4.2.4 on 2023-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.IntegerField(blank=True, max_length=16, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=5, null=True)),
                ('CVV', models.IntegerField(max_length=4)),
            ],
        ),
    ]
