# Generated by Django 4.2.4 on 2023-08-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_paycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycard',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
