# Generated by Django 4.2.4 on 2023-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_paycard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycard',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
