# Generated by Django 4.2.4 on 2023-08-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_paycard_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paycard',
            old_name='name',
            new_name='card_name',
        ),
    ]
