# Generated by Django 4.2.4 on 2023-08-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_name_paycard_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycard',
            name='CVV',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
