# Generated by Django 4.2.4 on 2023-08-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_paycard_cvv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayCard',
        ),
    ]
